# Generated by Django 3.1.1 on 2020-09-21 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('text', models.TextField()),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
